# Generated by Django 4.2 on 2023-05-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=100)),
                ('description', models.TextField(default='Non définie')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('acheve', models.CharField(choices=[('o', 'oui'), ('n', 'non')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('em', 'emballé'), ('fr', 'Frais'), ('cs', 'Conserve')], default='em', max_length=2)),
                ('description', models.TextField(default='Non définie')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fichier_CV', models.FileField(upload_to='')),
                ('fichier_photo', models.FileField(upload_to='')),
                ('lien_linkedln', models.URLField()),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='projet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.projet')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.service')),
            ],
        ),
    ]
