# Generated by Django 4.2 on 2023-05-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('cg', ': Charte graphique '), ('ob', 'Objet  3D'), ('Sc', 'Scénarisation')], default='em', max_length=2),
        ),
    ]
