# Generated by Django 4.2 on 2023-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
