# Generated by Django 4.2 on 2023-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_service_projet_alter_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='service',
            field=models.ManyToManyField(through='user.detail', to='user.service'),
        ),
    ]
