# Generated by Django 4.2 on 2023-05-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_service_projet_projet_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='equipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='personnel',
            field=models.ManyToManyField(to='user.personnel'),
        ),
        migrations.AddField(
            model_name='projet',
            name='equipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.equipe'),
        ),
    ]
