# Generated by Django 4.2 on 2023-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_personnel_equipe_personnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nom',
            field=models.CharField(default='non définie', max_length=100),
        ),
    ]
