# Generated by Django 4.2 on 2023-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_equipe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='fichier_CV',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fichier_photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
