# Generated by Django 4.2 on 2023-05-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_personnel_fichier_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='fichier',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
